# **Students Who Slip On Maths**

## Objectives

* Import the inital .csv file to a pandas dataframe for inspection

* Diagnose and make any necessary Transformations

* Engineer any features that may be needed or useful

* Cement the made changes into a new dataframe to be exported  to a new .csv


## Inputs

* The inital 'student_mat.csv'  

* Libraires containing the tools needed, pandas, numpy, matplotlib, seaborn. 

* A HelperFuncs.py with helper functions 

## Outputs

* A worked dataframe, exported to a .csv

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capstone_Three\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capstone_Three'

# Import block

In [4]:
# Libraries needed 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# Helper function
from HelperFuncs import InitialInspect

---

# Section 1 - Load

Load the raw .csv into a pandas dataframe

In [5]:
# Load the raw data
df_raw = pd.read_csv("Dataset/Raw/student_mat.csv", sep=";")

# View the dataframe
df_raw.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

Now to use the InitialInspect helper function to get the first look at the data

In [6]:
# Helper function
InitialInspect(df_raw)

Initial shape: (Row x Col) (395, 33)
==================================================
Columns data types:
 school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object
==================================================
Missing value counts:
school: 0.
sex: 0.
age: 0.
address: 0.
famsize: 0.
Pstatus: 0.
Medu: 0.
Fedu: 0.
Mjob: 0.
Fjob: 0.
reason: 0.
guardian: 0.
traveltime: 0.
studytime: 0.
failures: 0.
schoolsup: 0.
famsup: 0.
paid: 0.
activities: 0.
nursery: 0.
higher: 0.
internet: 0.
romantic: 0.
famrel: 0.
freetime: 0.
goout: 0.
Dalc: 0.
Walc: 0.
health: 0.
absences: 0.
G1: 0.
G2: 0.
G3: 0.
==================================================
Duplicate counts:
school: 393 duplicates.
sex: 393 duplicates.
age: 387 duplicates.
address: 393 duplicates.
famsize: 393 duplicates.
Pstatus: 393 duplicates.
Medu: 390 duplicates.
Fedu: 390 duplicates.
Mjob: 390 duplicates.
Fjob: 390 duplicates.
reason: 391 duplicates.
guardian: 392 duplicates.
traveltime: 391 duplicates.
studytime: 391 duplicates.
failures: 391 duplicates.
schoolsup: 393 duplicates.
famsup: 393 duplicates.
paid: 393 duplicates.
activities: 393 duplicates.
nursery: 393 duplicates.
higher: 393 duplicates.
internet: 393 duplicates.
romantic: 393 duplicates.
famrel: 390 duplicates.
freetime: 390 duplicates.
goout: 390 duplicates.
Dalc: 390 duplicates.
Walc: 390 duplicates.
health: 390 duplicates.
absences: 361 duplicates.
G1: 378 duplicates.
G2: 378 duplicates.
G3: 377 duplicates.
==================================================
The .describe summary:

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

==================================================
First 10 rows

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

==================================================

This summary shows that we have 395 rows and 33 columns. The datatypes all appear to be in order with no datetime infromation to handle. We already know there are no missing values from the dataset source and our massive amounts of duplicates is due to the nature of the information; being ranges or categories.

The .describe() summary shows that out important values like absences and final grade (G3) have no out of range errors which means we're not going to need any filtering or imputing, at least not right now.

With no cleaning needed to be done. We can move on to the transformations

---

# Section 2 - Transformations

As the dataset is quite clean, there's only going to be a couple transformations.

Firstly we'll make a 'studytime_label' column. As 'studytime' is in bins of 1-4, we'll apply that label into the dataset so that information can be seen.

In [7]:
# Applying the new column
df_raw["studytime_label"] = df_raw["studytime"].map({
    1: "< 2 hours",
    2: "2 - 5 hours",
    3: "5 - 10 hours",
    4: "> 10 hours"
})

# Inspect the new column
df_raw.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,studytime_label
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,2 - 5 hours
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,2 - 5 hours
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,2 - 5 hours
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,5 - 10 hours
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,2 - 5 hours
5,GP,M,16,U,LE3,T,4,3,services,other,...,4,2,1,2,5,10,15,15,15,2 - 5 hours
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,1,1,3,0,12,12,11,2 - 5 hours
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,1,4,1,1,1,6,6,5,6,2 - 5 hours
8,GP,M,15,U,LE3,A,3,2,services,other,...,2,2,1,1,1,0,16,18,19,2 - 5 hours
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,1,1,1,5,0,14,15,15,2 - 5 hours

Secondly, a handful of columns contain personal information that

---